[package]
name = "temp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.12.1"
chrono = "0.4"
winit = "0.27" 



#[build-dependencies]
#winresource = "0.1.17"
